### ISSUE TITLE
Configure Tailwind Settings in NextJS

### ISSUE THREAD

**Issue by davidrobertlowe** [sfusurge/stormhacks_website#12]
## Sub-Tasks

- [x] Configure tailwind settings and ensure tailwind is imported to the project
- [x] Add preset breakpoints for desktop and mobile screen sizes
- [x] Remove type-checking for Javascript files 
- [ ] Add default font sizes and weights for standard HTML selectors (e.g h1, h2, p, etc)
- [ ] Configure font family settings (consult with VD)
